### ISSUE TITLE
Raspberry Pi version

### ISSUE THREAD

**Issue by davidalben** [elad-bar/torque-api#1]
Hello. This MQTT Torque inegrations seems to be a great job.

I would like to use it in a Raspberry Pi 4, in which I have my broker, Home Assistant and other apps.

I don't know how hard should it be, but is it possible to publish an ARM32 version in Docker Hub?

Thank you.

**Comment by elad-bar** [comment]
Will try to handle it soon.

**Repository moved to GitLab**
Latest code and docker image available under the GitLab repo:

https://gitlab.com/elad.bar/torque-api
